#!/usr/bin/env python

import sys

device = sys.argv[1]

"""Assert that the device identifier is the given string."""
cmd = ('assert(' +
       ' || '.join(['getprop("ro.product.device") == "%s" || getprop("ro.build.product") == "%s"'
                     % (i, i) for i in device.split(",")]) +
       ' || abort("This package is for device: %s; ' +
       'this device is " + getprop("ro.product.device") + ".");' +
       ');') % device
print(cmd)
