#!/bin/sh
# Fix up mount points device node names.
# This is broken pending systemd > 191-2 so hack the generated unit files :(
# See: https://bugzilla.redhat.com/show_bug.cgi?id=859297

DEVICE=$1
shift

echo "Fixing mount-points for device $DEVICE"

case "$DEVICE" in
    "hammerhead")
        sed -i \
            -e 's block/platform/msm_sdcc.1/by-name/modem mmcblk0p1 ' \
            -e 's block/platform/msm_sdcc.1/by-name/persist mmcblk0p16 ' \
            -e 's block/platform/msm_sdcc.1/by-name/system mmcblk0p25 ' \
            -e 's block/platform/msm_sdcc.1/by-name/userdata mmcblk0p28 ' \
            "$@"
        ;;

    "mako")
        sed -i \
            -e 's block/platform/msm_sdcc.1/by-name/modem mmcblk0p1 ' \
            -e 's block/platform/msm_sdcc.1/by-name/persist mmcblk0p20 ' \
            -e 's block/platform/msm_sdcc.1/by-name/system mmcblk0p21 ' \
            -e 's block/platform/msm_sdcc.1/by-name/userdata mmcblk0p23 ' \
            "$@"
        ;;

    "grouper")
        sed -i \
            -e 's block/platform/sdhci-tegra.3/by-name/APP mmcblk0p3 ' \
            -e 's block/platform/sdhci-tegra.3/by-name/CAC mmcblk0p4 ' \
            -e 's block/platform/sdhci-tegra.3/by-name/UDA mmcblk0p9 ' \
            -e 's block/platform/sdhci-tegra.3/by-name/MSC mmcblk0p5 ' \
            -e 's block/platform/sdhci-tegra.3/by-name/LNX mmcblk0p2 ' \
            -e 's block/platform/sdhci-tegra.3/by-name/SOS mmcblk0p1 ' \
            "$@"
        ;;

    "tilapia")
        sed -i \
            -e 's block/platform/sdhci-tegra.3/by-name/APP mmcblk0p3 ' \
            -e 's block/platform/sdhci-tegra.3/by-name/CAC mmcblk0p5 ' \
            -e 's block/platform/sdhci-tegra.3/by-name/UDA mmcblk0p10 ' \
            -e 's block/platform/sdhci-tegra.3/by-name/MSC mmcblk0p6 ' \
            -e 's block/platform/sdhci-tegra.3/by-name/LNX mmcblk0p2 ' \
            -e 's block/platform/sdhci-tegra.3/by-name/SOS mmcblk0p1 ' \
            "$@"
        ;;

    "i9305" | "encore" | "n7000" | "n7100" | "i9300" | "iyokan")
	sed -i \
	    -e 's /block/ / ' \
	    "$@"
	;;

    "p3110")
        sed -i \
            -e 's block/platform/omap/omap_hsmmc.1/by-name/DATAFS mmcblk0p10 ' \
            -e 's block/platform/omap/omap_hsmmc.1/by-name/KERNEL mmcblk0p5 ' \
            -e 's block/platform/omap/omap_hsmmc.1/by-name/FACTORYFS mmcblk0p9 ' \
            -e 's block/platform/omap/omap_hsmmc.1/by-name/EFS mmcblk0p1 ' \
            -e 's block/platform/omap/omap_hsmmc.1/by-name/CACHE mmcblk0p7 ' \
            "$@"
        ;;

    "maguro")
        sed -i \
            -e 's block/platform/omap/omap_hsmmc.0/by-name/system mmcblk0p10 ' \
            -e 's block/platform/omap/omap_hsmmc.0/by-name/cache mmcblk0p11 ' \
            -e 's block/platform/omap/omap_hsmmc.0/by-name/userdata mmcblk0p12 ' \
            -e 's block/platform/omap/omap_hsmmc.0/by-name/misc mmcblk0p5 ' \
            -e 's block/platform/omap/omap_hsmmc.0/by-name/boot mmcblk0p7 ' \
            -e 's block/platform/omap/omap_hsmmc.0/by-name/recovery mmcblk0p8 ' \
            -e 's block/platform/omap/omap_hsmmc.0/by-name/sbl mmcblk0p2 ' \
            -e 's block/platform/omap/omap_hsmmc.0/by-name/xloader mmcblk0p1 ' \
            -e 's block/platform/omap/omap_hsmmc.0/by-name/radio mmcblk0p9 ' \
            -e 's block/platform/omap/omap_hsmmc.0/by-name/efs mmcblk0p3 ' \
            "$@"
        ;;

    "bacon")
        sed -i \
            -e 's block/platform/msm_sdcc.1/by-name/modem mmcblk0p1 ' \
            -e 's block/platform/msm_sdcc.1/by-name/persist mmcblk0p15 ' \
            -e 's block/platform/msm_sdcc.1/by-name/system mmcblk0p14 ' \
            -e 's block/platform/msm_sdcc.1/by-name/userdata mmcblk0p28 ' \
            "$@"
        ;;
    "ace")
       sed -i \
            -e 's block/platform/msm_sdcc.2/by-num/p25 mmcblk0p25 ' \
            -e 's block/platform/msm_sdcc.2/by-num/p26 mmcblk0p26 ' \
            -e 's block/platform/msm_sdcc.2/by-num/p27 mmcblk0p27 ' \
            -e 's block/platform/msm_sdcc.2/by-num/p28 mmcblk0p28 ' \
            "$@"
        ;;
    "deb")
        sed -i \
            -e 's block/platform/msm_sdcc.1/by-name/persist mmcblk0p4 ' \
            -e 's block/platform/msm_sdcc.1/by-name/boot mmcblk0p14 ' \
            -e 's block/platform/msm_sdcc.1/by-name/system mmcblk0p22 ' \
            -e 's block/platform/msm_sdcc.1/by-name/userdata mmcblk0p31 ' \
            "$@"
        ;;
    "flo")
        sed -i \
            -e 's block/platform/msm_sdcc.1/by-name/persist mmcblk0p4 ' \
            -e 's block/platform/msm_sdcc.1/by-name/boot mmcblk0p14 ' \
            -e 's block/platform/msm_sdcc.1/by-name/system mmcblk0p22 ' \
            -e 's block/platform/msm_sdcc.1/by-name/userdata mmcblk0p30 ' \
            "$@"
        ;;
    "yuga")
        sed -i \
            -e 's block/platform/msm_sdcc.1/by-name/boot mmcblk0p17 ' \
            -e 's block/platform/msm_sdcc.1/by-name/system mmcblk0p24 ' \
            -e 's block/platform/msm_sdcc.1/by-name/cache mmcblk0p25 ' \
            -e 's block/platform/msm_sdcc.1/by-name/userdata mmcblk0p26 ' \
            -e 's block/platform/msm_sdcc.1/by-name/LTALabel mmcblk1 ' \
            "$@"
        ;;
    *)
	cat <<EOF

****************************************************************
****************************************************************
ERROR: $DEVICE does not have mountpoint fixup data - see
       SailfishOS HADK for details on how to fix this
       Check: device/$VENDOR/$DEVICE/recovery.fstab
****************************************************************
****************************************************************

EOF
        exit 1
        ;;
esac

