#! /bin/sh
#
# Hybris adaptation bootstrapping initramfs init script.
#
# Copyright (c) 2013 Tom Swindell <t.swindell@rubyx.co.uk>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License version 2 as published by the
# Free Software Foundation.
#
# Authors:
#   - Tom Swindell <t.swindell@rubyx.co.uk>
#
get_opt() {
  for param in $(cat /proc/cmdline); do
    echo "$param" | grep "^$1=*" | cut -d'=' -f2
  done
}

write() {
  /bin/echo -n "$2" > "$1"
}

usb_net() {
  LOCAL_IP=192.168.2.1
  ANDROID_USB=/sys/class/android_usb/android0

  case "$1" in
    start)
      write $ANDROID_USB/enable        0
      write $ANDROID_USB/idVendor      18D1
      write $ANDROID_USB/idProduct     D001
      write $ANDROID_USB/iManufacturer "Mer"
      write $ANDROID_USB/iProduct      "Boat Loader"
      write $ANDROID_USB/iSerial       $(grep 'Serial' /proc/cpuinfo | awk '{print $3}')
      write $ANDROID_USB/functions     rndis
      write $ANDROID_USB/enable        1

      sleep 2

      /bin/ifconfig usb0   $LOCAL_IP && USB_IFACE=usb0
      /bin/ifconfig rndis0 $LOCAL_IP && USB_IFACE=rndis0

      /bin/echo "interface $USB_IFACE" >> /etc/udhcpd.conf

      udhcpd
      telnetd -p 23 -l /bin/sh -F
      ;;

    stop)
      write $ANDROID_USB/enable 0
      ;;
  esac
}

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

/bin/busybox --install -s

mkdir /dev
mount -t tmpfs tmpfs /dev

mkdir /dev/pts
mkdir /proc
mkdir /sys

mount -a
ln -s /proc/mounts /etc/mtab

echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

sleep 2

zcat /bootsplash.gz > /dev/fb0

BOARDNAME=$(grep 'Hardware' /proc/cpuinfo | awk '{print $3}')

case "$BOARDNAME" in
  grouper)
    DATA_PARTITION=/dev/mmcblk0p9
    ;;
  tilapia)
    DATA_PARTITION=/dev/mmcblk0p10
    ;;
esac

if [ ! -z $DATA_PARTITION ]; then
  mkdir /data
  mkdir /target

  mount $DATA_PARTITION /data
  mount --bind /data/.stowaways/sffe /target
fi

# Check for special bootmode flags and process accordingly.
case "$(get_opt bootmode)" in
  debug)
    usb_net start
    ;;

  *)
    if [ -f "/target/init-debug" ]; then
      exec switch_root /target /init-debug &> /target/init-debug-stderrout
    else
      exec switch_root /target /sbin/init --log-level=debug --log-target=kmsg &> /target/init-stderrout
    fi
    usb_net start
    ;;
esac

sleep 86400

